// supabaseAdmin.js
// Optional integration: if SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY are set
// in the environment, every AI reply generated by ai.js is also written
// into the `support_messages` table (sender: 'ai'), so it shows up in the
// same thread that support.html renders and that the admin console
// already monitors.
//
// This uses the SERVICE ROLE key deliberately, on the server only. The
// browser's anon key is restricted by RLS to inserting sender='visitor'
// rows — it cannot and should not be able to write 'ai' or 'admin' rows.
// Never put the service role key in support.html or any client-side file.

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

let client = null;

if (SUPABASE_URL && SUPABASE_SERVICE_ROLE_KEY) {
  const { createClient } = require('@supabase/supabase-js');
  client = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: { persistSession: false },
  });
  console.log('supabaseAdmin.js: Supabase persistence enabled for AI replies');
} else {
  console.log('supabaseAdmin.js: SUPABASE_URL/SUPABASE_SERVICE_ROLE_KEY not set — running without persistence');
}

// threadId here IS the sessionId the browser sends — support.js passes its
// Supabase support_threads.id as the chat sessionId so the two line up.
async function persistAiReply(threadId, text) {
  if (!client || !threadId || !text) return;
  try {
    const { error } = await client.from('support_messages').insert({
      thread_id: threadId,
      sender: 'ai',
      message: text,
    });
    if (error) throw error;
  } catch (err) {
    // Never let a persistence failure break the chat response itself —
    // the browser already has the reply from the HTTP response body.
    console.warn('supabaseAdmin.js: failed to persist AI reply:', err.message);
  }
}

module.exports = { persistAiReply, isEnabled: () => !!client };
